### PR TITLE
Update mt940.pest

### PR DESCRIPTION
**Pull request by lgromanowski**
Added missing Swift code

### CODE REVIEW

**Comment by svenstaro** [comment]
Hey, could you also expand the tests to include this flag and perhaps link some docs where you find this to be a documented field?

**Comment by lgromanowski** [comment]
Hi,
sure, I'll add tests in a few days. Link to the documentation: 
- https://www.ing.nl/media/MT_940_Customer_Statement_Message_20180829_0731_tcm162-156566.pdf - page 7, "Transaction type"
- https://docplayer.net/14759220-Customer-statement-mt940-with-structured-information-to-account-owner.html - page 6, subfield 6 "Transaction type identification code"

**Comment by svenstaro** [comment]
It would also be neat if you had an example file with this flag set that you could add to our test base. The tests are fairly easy to add stuff to.

**Comment by svenstaro** [comment]
@lgromanowski Hey, I'd still like to merge this but I'm just curious whether you have some test file that makes use of this field.

**Comment by svenstaro** [comment]
Feel free to re-open if you are still interested in this.

**Pull request closed without merging**
