### PR TITLE
Add tag 28

### PR DESCRIPTION
**Pull request by twistedfall**
According to ABN Amro docs tag 28 is synonymous to tag 28C and I encounter those in my statements.

Also reduced and optimized some unnecessary allocations.

### CODE REVIEW

**Comment by svenstaro** [comment]
Thanks for your contribution! According to [this](https://www.abnamro.nl/nl/images/Generiek/PDFs/020_Zakelijk/03_OfficeNet/Formatenboek_MT94_(engels).pdf) document, both `28C` and `28` can indeed occur with a single difference:

image

I'm attaching this as a screenshot as the layout is important. So does this mean that for `:28:` it's `5N[/2N]` and for `:28C` it's `5N/(/3N)` or that it's either of the formats for either of the tags?

**Comment by svenstaro** [comment]
In another document, I found a note that until 1999, `:28:` was ok but since then `:28C:` should be used since it apparently allows for more pages to be printed in a statement. I'd be OK with supporting the old format, however, but we should figure out what the actual allowed format is.

**Comment by svenstaro** [comment]
By the way, is there any chance you could contribute some integration testing data for this?

**Comment by svenstaro** [comment]
According to my benchmarks (`cargo bench`), the allocation stuff doesn't really give us any better performance. Most of the time is lost in the parsing part. I suppose it's more proper, though, so might as well have it in.

**Comment by twistedfall** [comment]
Thanks, let me work on your comments :)

**Comment by twistedfall** [comment]
> I'm attaching this as a screenshot as the layout is important. So does this mean that for :28: it's 5N[/2N] and for :28C it's 5N/(/3N) or that it's either of the formats for either of the tags?

I wonder that myself, in my statements they are presented as `:28:24101/1` so, nothing definitive.

> By the way, is there any chance you could contribute some integration testing data for this?

I've updated the commits with a (heavily redacted) copy of the statement.

**Comment by svenstaro** [comment]
Thanks, looks great. One thing I'm pondering: should we use the same proptest that we use for :28C: already? It would cut down on a lot of duplication and we'd only have to sometimes generate tag names with a trailing C and sometimes without.

We apparently can't find out the differences anyway. What do you think?

**Comment by twistedfall** [comment]
Makes perfect sense, of course! Fix applied

**Comment by svenstaro** [comment]
Ok, everything seems fine. Thanks a bunch!

Out of curiosity, what are you using this project for? :)

**Comment by twistedfall** [comment]
> Out of curiosity, what are you using this project for? :)

:)) Nothing too fancy, I’m just getting the list of transactions from the bank to import into a budgeting app

**Comment by svenstaro** [comment]
Cool!

**Pull request merged**
